-- Recreate orders table (clean for production)
CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    customer_name TEXT,
    customer_phone TEXT,
    customer_email TEXT,
    customer_address TEXT,
    total_amount REAL,
    order_status TEXT NOT NULL DEFAULT 'pending',
    payment_status TEXT DEFAULT 'pending',
    payment_link TEXT,
    payment_response TEXT,
    snap_token TEXT,
    shipping_status TEXT,
    shipping_area TEXT,
    shipping_notes TEXT,
    pickup_method TEXT,
    tipe_pesanan TEXT,
    tracking_number TEXT,
    courier_service TEXT,
    lokasi_pengiriman TEXT,
    lokasi_pengambilan TEXT,
    assigned_deliveryman_id TEXT,
    admin_note TEXT,
    picked_up_by TEXT,
    pickup_date TEXT,
    pickup_time TEXT,
    delivery_date TEXT,
    delivery_time TEXT,
    readyForPickup_photo_url TEXT,
    pickedUp_photo_url TEXT,
    delivered_photo_url TEXT,
    created_by_admin_id TEXT,
    created_by_admin_name TEXT,
    outlet_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
