name: Run D1 Migrations (Manual)

on:
  workflow_dispatch:
    inputs:
      databaseName:
        description: 'D1 Database name (e.g., order-management-prod)'
        required: true
        default: 'order-management-prod'
      sqlFile:
        description: 'Path to SQL file under migrations/ (e.g., migrations/0015_new_change.sql)'
        required: true
        default: 'migrations/0015_new_change.sql'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler v4
        run: |
          npm install --no-audit --no-fund --save-dev wrangler@4

      - name: Apply migrations to production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "Applying ${{ github.event.inputs.sqlFile }} to DB ${{ github.event.inputs.databaseName }}"
          npx wrangler d1 execute "${{ github.event.inputs.databaseName }}" --file "${{ github.event.inputs.sqlFile }}" --remote --env production
